### ISSUE TITLE
Incorrect repository link on project page

### ISSUE THREAD

**Issue by Kristine1975** [icethrush/repulsive-curves#6]
The link to the Github repository on the project page at https://www.cs.cmu.edu/~christoy/Projects/RepulsiveSurfaces.html is incorrect. It is:

> https://github.com/icethrush/repulsive-surfaces

It should be:

> https://github.com/icethrush/repulsive-curves

**Comment by icethrush** [comment]
Hi, thanks for the comment. We have actually published two papers, which have their own paper pages and repos. The corresponding project page for this repo (repulsive-curves) is: https://www.cs.cmu.edu/~christoy/Projects/RepulsiveCurves.html
